name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: actions/cache@v5
        with:
          path: ~/.elm
          key: elm-lint-${{ hashFiles('review/elm.json') }}

      - run: npm ci

      - name: elm-format validate
        run: npx elm-format --validate src/ review/ script/ examples/minimal/src/ examples/minimal/snapshot-tests/src/ examples/features/src/ examples/features/snapshot-tests/src/ examples/log-formatter/src/ examples/log-formatter/snapshot-tests/src/ examples/program-test/src/ examples/program-test/snapshot-tests/src/

      - name: elm-review
        run: npx elm-review

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [minimal, log-formatter, features, program-test]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - id: cache-node_modules
        uses: actions/cache@v5
        with:
          path: examples/${{ matrix.example }}/node_modules
          key: node_modules-${{ matrix.example }}-${{ hashFiles(format('examples/{0}/package.json', matrix.example), format('examples/{0}/package-lock.json', matrix.example)) }}

      - uses: actions/cache@v5
        with:
          path: ~/.elm
          key: elm-${{ matrix.example }}-${{ hashFiles(format('examples/{0}/snapshot-tests/elm.json', matrix.example)) }}

      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: examples/${{ matrix.example }}

      - run: npm test -- --ci
        working-directory: examples/${{ matrix.example }}

  publish:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: dillonkearns/elm-publish-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
